name: Continous Integration
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v2
        with:
         path: backend/node_modules
         key: node-modules-cache

      - name: Checkout 
        uses: actions/checkout@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd backend && npm install

      - name: Build the project
        run: cd backend && npm run build

      - name: Generate Artifacts
        run: cd backend/build && zip -r artifact.zip ./ -x '*.git*'
          

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: backend-artifact
          path: backend/build/artifact.zip